# Metadata
title: Judul Skripsi
author: Penulis Skripsi
nim: 24060118130999
date: 1 Januari 2023
keywords: skripsi, informatika
subject: Judul skripsi
# Bahasa
lang: id
dir: rtl
# Latex
# Layout
classoption: portrait
documentclass: report
geometry:
  - top=3cm
  - bottom=2.5cm
  - left=3cm
  - right=2.5cm
indent: true
linestretch: 1.5
pagestyle: plain
papersize: A4
secnumdepth: 4
# Fonts
fontsize: 12pt
mainfont: Times New Roman
# Front matter
lof: true
lot: true
toc: true
toc-depth: 4
# Back matter
reference-section-title: "Daftar Pustaka"
# Override
numbersections: 4
header-includes:
  - \input{hacks/debug.tex}
  - \input{hacks/maketitle.tex}
  - \input{hacks/footer.tex}
  - \input{hacks/paragraph.tex}
  - \input{hacks/heading.tex}
  - \input{hacks/numbering.tex}
include-before:
  - \input{frontmatter/pernyataan.tex}
  - \input{frontmatter/pengesahan.tex}
  - \input{frontmatter/pengantar.tex}
  - \input{frontmatter/persetujuan.tex}
  - \input{frontmatter/abstrak.tex}
  - \input{frontmatter/abstract.tex}
include-after:
  - \input{backmatter/lampiran.tex}
